before:
  hooks:
    - go mod download
builds:
  - id: darwin-amd64
    env:
      - CGO_ENABLED=1  
      - CC=o64-clang 
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64 
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64 
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: go-jwlm
    repository:
      owner: andreassko
      name: homebrew-go-jwlm
    homepage: https://github.com/AndreasSko/go-jwlm
