name: Test coverage
on: pull_request
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -race -covermode atomic -coverprofile=profile.cov ./...
      - name: Convert .cov to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: profile.cov
          outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
