name: CI
on: [push]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use github.com/AndreasSko/jwpub-snippets instead of fake implementation
        uses: AndreasSko/find-and-replace-action@main
        with:
          from: ^replace github.com\/AndreasSko\/jwpub-snippets.*$
          to: ""
          files: go.mod

      - name: Inject insteadOf config for private repo
        env:
          JWPUB_SNIPPET_GITHUB_TOKEN: ${{ secrets.JWPUB_SNIPPET_GITHUB_TOKEN }}
        run: git config --global url."https://${JWPUB_SNIPPET_GITHUB_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"

      - run: go get
        env:
          GOPRIVATE: github.com/AndreasSko

      - name: Run tests
        run: go test ./...
    
  gomobile-ios:
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Gomobile
        run: go get golang.org/x/mobile/cmd/gomobile

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use github.com/AndreasSko/jwpub-snippets instead of fake implementation
        uses: AndreasSko/find-and-replace-action@main
        with:
          from: ^replace github.com\/AndreasSko\/jwpub-snippets.*$
          to: ""
          files: go.mod

      - name: Inject insteadOf config for private repo
        env:
          JWPUB_SNIPPET_GITHUB_TOKEN: ${{ secrets.JWPUB_SNIPPET_GITHUB_TOKEN }}
        run: git config --global url."https://${JWPUB_SNIPPET_GITHUB_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"

      - run: go get
        env:
          GOPRIVATE: github.com/AndreasSko
        
      - name: Initialize Gomobile
        run: go mod download golang.org/x/mobile && gomobile init
        working-directory: gomobile

      - name: Build for iOS
        run: gomobile bind -target ios -v
        working-directory: gomobile
