name: CI
on: [push]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Use github.com/AndreasSko/jwpub-snippets instead of fake implementation
        uses: jacobtomlinson/gha-find-replace@0.1.4
        with:
          include: go.mod
          find: ^replace github.com\/AndreasSko\/jwpub-snippets.*$
          replace: ""

      - name: Inject insteadOf config for private repo
        env:
          JWPUB_SNIPPET_GITHUB_TOKEN: ${{ secrets.JWPUB_SNIPPET_GITHUB_TOKEN }}
        run: git config --global url."https://${JWPUB_SNIPPET_GITHUB_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"

      - run: go mod tidy
        env:
          GOPRIVATE: github.com/AndreasSko

      - name: Run tests
        run: go test ./...
    
  gomobile-ios:
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Gomobile
        run: go get golang.org/x/mobile/cmd/gomobile

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
        
      - name: Initialize Gomobile
        run: gomobile init
        working-directory: gomobile

      - name: Use github.com/AndreasSko/jwpub-snippets instead of fake implementation
        uses: jacobtomlinson/gha-find-replace@0.1.4
        with:
          include: go.mod
          find: ^replace github.com\/AndreasSko\/jwpub-snippets.*$
          replace: ""

      - name: Inject insteadOf config for private repo
        env:
          JWPUB_SNIPPET_GITHUB_TOKEN: ${{ secrets.JWPUB_SNIPPET_GITHUB_TOKEN }}
        run: git config --global url."https://${JWPUB_SNIPPET_GITHUB_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"

      - run: go mod tidy
        env:
          GOPRIVATE: github.com/AndreasSko

      - name: Build for iOS
        run: gomobile bind -target ios -v
        working-directory: gomobile
