name: Release
on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        run: docker run -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --rm --privileged -v $GITHUB_WORKSPACE:/go/src/github.com/AndreasSko/go-jwlm -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/AndreasSko/go-jwlm mailchain/goreleaser-xcgo --rm-dist
