name: Release
on:
  push:
    tags:
      - '*'
    paths:
      - ".github/workflows/release.yml"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        run: docker run -e GITHUB_TOKEN=${{ secrets.GORELEASER_GITHUB_TOKEN }} --rm --privileged -v $GITHUB_WORKSPACE:/go/src/github.com/AndreasSko/go-jwlm -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/AndreasSko/go-jwlm andreassko/goreleaser-xcgo --rm-dist
